builds:
  - binary: habit
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: habit
    homepage: "https://github.com/qba73/habit"
    tap:
      owner: qba73
      name: homebrew-tap
    commit_author:
      name: qba73
      email: info@jarosz.dev
    description: "A cli tool for tracking daily habits."
    install: |
      bin.install "habit"

checksum:
  name_template: "checksums.txt"
